### ISSUE TITLE
Use one directory per odoo version instead of using only one repo

### ISSUE THREAD

**Issue by nda-odoo** [brinkflew/odev#6]
A bit like : https://github.com/odoo/ps-custom/blob/84242f8cf917520248b1aa52d27618ea3b5b3e44/.global.sh#L344

**Comment by brinkflew** [comment]
@nda-odoo We can probably include that in there: https://github.com/brinkflew/odev/blob/fd8781bdc93a0f9b429e925c8aaf2f4dfd98d647/src/scripts/run.py#L24-L44

We already have one directory per odoo version, I guess we can add a venv directory in the same "root" dir
